# an object has two characteristics:
#    1.attributes( name, age,colour)
#    2.behaviour(learn,study,singing,dance)

# class:class is blueprint of the object
# object:physical entity and blueprint of class

In [ ]:
# class classNAme:
# some functions and variables
# function--used to perform specific activity
# variables----data(memory)
    
#    

In [16]:
class Demo:
    def test(self):
        print("test() for the class and method")
        return
obj=Demo()
obj.test()

test() for the class and method


In [17]:
def test():
    print("test for function")
    return
test()

test for function


In [23]:
# FACTORIAL OF A NUMBER
class Demo1:
    def fact(self,n):
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact     
p1=Demo1()
print(p1.fact(5))

120


In [25]:
class Demo2:
   
    def accept(self,p1,p2):
        a=p1
        b=p2
        return
    def display(self):
        print("p1=",a)
        print("p2=",b)
c1=Demo2()
c1.accept(10,20)
c1.display()

NameError: name 'a' is not defined

In [30]:
class Demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
    def add(self,p1,p2):
        return p1+p2
c1=Demo2(10,20)
print(c1.add(100,200))

300


In [34]:
class Person():
    #Constructor
    def __init__(self,name):
        self.name = name
    def getName(self):
        return self.name
    def isEmployee(self):
        return False

#Derived Class
class Employee(Person):
    def isEmployee(self):
        return True  
emp=Person("ghfgh")
print(emp.getName(),emp.isEmployee())
emp1=Employee("fghdh")
print(emp1.getName(),emp1.isEmployee())

ghfgh False
fghdh True


In [1]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)

[1 2 3 4]


In [2]:
lst=[1,2,3,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
int32


In [3]:
lst=[1,2,3,4]
print(lst)

[1, 2, 3, 4]


In [6]:
a1=np.array([(1,2,3),(4,5,6,)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)


(2, 3)
(3, 2)


In [7]:
# Re-shape the givn array
# numpy.reshape(arrayName,reshape,order='c')
a1=np.array([(1,2,3),(4,5,6,)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
# append some data --- horizontally
# append some data --- vertical
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [9]:
#append some data --- verically
# vstack(array1,array2) --- will be automatically arranged in vertical
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [10]:
# numpy.zeros() and numpy.one()
# Generate an array with all zeros-- numpy.zeros()
# numpy.zeros(shape,dtype=float-,order='C')
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [12]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [11]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2]=5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [13]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3]=14
np.asarray(A)[3][3]=16
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [1]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [3]:
np.arange(2,20,2)
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [11]:
# indexing and slicing of numpy
a1=np.array([(1,2,3),(4,5,6)])
print("first row=",a1[0])

first row= [1 2 3]


In [8]:
a1=np.array([(1,2,3),(4,5,6)])
print("second row=",a1[1])

second row= [4 5 6]


In [16]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing row=",a1[:,1])

slicing row= [2 5]


In [14]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing last column",a1[:,2])

slicing last column [3 6]


In [15]:
a1=np.array([(1,2,3),(47,5,6)])
print("row and column",a1[1:,1])

row and column [5]


In [17]:
a1=np.random.normal(5,1,10)
print(a1)
print("Min value=",np.min(a1))
print("Max value=",np.max(a1))
print("Mean value=",np.mean(a1))
print("Median value=",np.median(a1))

[5.17177394 4.49352758 4.67040278 3.96788447 6.34068998 5.22456996
 4.55674226 4.76878886 2.60327346 4.4650809 ]
Min value= 2.6032734589727053
Max value= 6.340689976809729
Mean value= 4.626273418387145
Median value= 4.613572517774055


In [18]:
# Multiply of ID arrays
# numpy.dot(x,y)---
c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [20]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

# pandas basics
## pandas dataframes
### data analysis with python


In [1]:
import pandas as pd
dict={"name":["anil","akhil","dinesh","harsha","ajay","kranth"],"emailid":["anil@gmail.com","akhil@gmail.com","dinesh@gmail.com","harsha@gmail.com","ajay@gmail.com","kranth@gmail.com"],"mobile":[999,222,456,485,258,265]}
b=pd.DataFrame(dict)
print(b)

     name           emailid  mobile
0    anil    anil@gmail.com     999
1   akhil   akhil@gmail.com     222
2  dinesh  dinesh@gmail.com     456
3  harsha  harsha@gmail.com     485
4    ajay    ajay@gmail.com     258
5  kranth  kranth@gmail.com     265


In [3]:
b.index=["01","02","03","04","05","06"]
print(b)

      name           emailid  mobile
01    anil    anil@gmail.com     999
02   akhil   akhil@gmail.com     222
03  dinesh  dinesh@gmail.com     456
04  harsha  harsha@gmail.com     485
05    ajay    ajay@gmail.com     258
06  kranth  kranth@gmail.com     265


In [3]:
def frequency(a):
    i=0
    while(i<=9):
        count=0
        for j in range(len(a)):
            if(ord(a[j])>=48 and ord(a[j])<=56):
                if i==int(a[j]):
                    count=count+1
        print(count,end=" ")
        i=i+1
a="213abc456def111"
frequency(a)


0 4 1 1 1 1 1 0 0 0 

In [4]:
def check(s1, s2): 
      
    # the sorted strings are checked  
    if(sorted(s1)== sorted(s2)): 
        print("The strings are anagrams.")  
    else: 
        print("The strings aren't anagrams.")          
          
# driver code   
s1 ="listen"
s2 ="silent" 
check(s1, s2) 

The strings are anagrams.
